!wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww!
!---------------------------------------------------------------------!
!                    MESH GENERATOR USING A Gmsh FILE                 !
!                                Jun 2013                             !
!---------------------------------------------------------------------!
!wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww!

      SUBROUTINE MeshGMsh

!---------------------------------------------------------------------!
!                                                                     !
!    This program generates a the corresponding data file needed to   !
!    the nsmp3D program using the mesh generated by the program       !
!    GMesh by vtk. We need to read the following data:                !
!                                                                     !
!         - The number of vertices,                                   !
!         - The number of elements,                                   ! 
!         - The vertex coordinates                                    !
!         - The type of element: inside or BC (third column)          !
!         - A value at each vertex that can be used as depth          !
!           (fourth column)                                           !
!         - The corresponding vertex index for each element.          !
!                                                                     !
!---------------------------------------------------------------------!
!                                                                     !
!    Parameters & variables:                                          !
!   _______________________________________________________________   !
!  |   Name          |                 Description                 |  !  
!  |_________________|_____________________________________________|  !
!  | TotalV          |  Total number de vertex                     |  !
!  | TotalE          |  Total number of cells                      |  !
!  | v1,v2,v3        |  Numbering of the vertex of each element    |  !
!  | c1,c2,c3        |  Numbering of the cell center neighborn     |  !
!  | irec            |  Writing file                               |  !           
!  |_________________|_____________________________________________|  !
!                                                                     !
!   WARNING: We need to eliminate the points and the lines form the   !
!            file.vtk. They are added in the number of elements.      !
!                                                                     ! 
!---------------------------------------------------------------------!

!*********************************************************************!
!                                                                     !
!                           Definitions                               !
!                                                                     !
!*********************************************************************!
!      ____________________________________
!     |                                    |
!     |      Declaration of variables      |
!     |____________________________________|

      implicit none
!     ------------------------------------------
      real*8, dimension(:),allocatable :: xxv,yyv
      real*8, dimension(:),allocatable :: BottomH
      integer,dimension(:),allocatable :: v1,v2,v3
      integer,dimension(:),allocatable :: c1,c2,c3
      integer,dimension(:),allocatable :: tag1
      integer,dimension(:),allocatable :: tbe
      integer,dimension(:),allocatable :: tbv
      integer,dimension(:),allocatable :: vbdy1,vbdy2,vbdy3
      integer,dimension(:),allocatable :: Esample
      integer,dimension(:),allocatable :: Vsample
      integer,dimension(:,:),allocatable :: aux      
!     ------------------------------------------
      integer:: TotalV,TotalE
      integer:: Nvwallsbdy,Nvdischbdy,Nvwaterbdy
      integer:: Nesample,Nvsample
      integer:: ind1,ind2,ind3,vertex1,vertex2
      integer:: ii,i,j,nc,nv
      integer:: irec
!     ----------------------------------
      real*8, dimension(:),allocatable :: xxc,yyc
      integer :: jv1,jv2,jv3,s1,s2,s3
      integer :: ed,TotalEdges
      integer :: DoThis,Maux
      real*8  :: Raux
!     ------------------------------------------
      real*8  :: YDIni,rE,rI,dd,dC1,dC2
!     ------------------------------------------
      character*40 filename,fileread
      character*80 title
!     ------------------------------------------
      integer,parameter :: IDISPLAY = 1
!     ------------------------------------------

!*********************************************************************!
!                                                                     !
!                           Initialization                            !
!                                                                     !
!*********************************************************************!

!     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     ifdef KeyDbg
        write(*,'(t8,60a)') '----> Begin subroutine: MeshGMesh'
#     endif
!     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!      ________________________________________________________
!     |                                                        |
!     |                        Real NCELL0                     |
!     |________________________________________________________|

      open(22,file='Gmsh.vtk',status='OLD')
      read(22,'(A46)') title
      read(22,'(A46)') title
      read(22,'(A46)') title
      read(22,'(A46)') title
      read(22,*) title,TotalV,title 
      do nv=1,TotalV
         read(22,'(A46)') title
      enddo
      read(22,'(A46)') title 
!     ----------------------------      
      read(22,*) title,TotalE,Maux
      s1 = 0
      s2 = 0
      s3 = 0
      do i=1,TotalE     
         read(22,*) Maux
         if (Maux.eq.1) s1 = s1 + 1
         if (Maux.eq.2) s2 = s2 + 1
         if (Maux.eq.3) s3 = s3 + 1
      enddo
!     ----------------------------   
      close(22)
      
!      ________________________________________________________
!     |                                                        |
!     |                    Read file: Gmesh.vtk                |
!     |________________________________________________________|

      if (IDISPLAY.eq.1) then
         print*,' '
         print*,' ==================================================='
         print*,'          This is the Gmesh data file               '
         print*,' ==================================================='
         print*,' '
      endif
!     ________________________________________________________
!     Open file
      open(22,file='Gmsh.vtk',status='OLD')
      read(22,'(A46)') title
      read(22,'(A46)') title
      read(22,'(A46)') title
      read(22,'(A46)') title
!     ________________________________________________________
!     Read: Number of vertex points 
      read(22,*) title,TotalV,title
!     ________________________________________________________
      allocate(xxv(TotalV))
      allocate(yyv(TotalV))
      allocate(tag1(TotalV))
      do nv=1,TotalV
         read(22,*) xxv(nv),yyv(nv),Raux
         tag1(nv) = 0
      enddo
!     ________________________________________________________
!     Read: Number of cells
      read(22,'(A46)') title 
      read(22,*) title,TotalE,Maux
!     ________________________________________________________
      allocate(aux(TotalE,3))
      allocate(xxc(TotalE))
      allocate(yyc(TotalE))
      allocate(v1(TotalE))
      allocate(v2(TotalE))
      allocate(v3(TotalE))
!     ________________________________________________________ 
      do i=1,s1
         read(22,'(A46)') title
      enddo
      do i=1,s2
         read(22,'(A46)') title
      enddo
      do i=1,s3
         read(22,*) Maux,v1(i),v2(i),v3(i)
         v1(i) = v1(i) + 1
         v2(i) = v2(i) + 1
         v3(i) = v3(i) + 1
      enddo
      print*,'      N_VERT  = ',TotalV
      print*,' Gmsh Element = ',TotalE
      print*,' Real N_CELL0 = ',s3
      TotalE = s3    
!     ________________________________________________________
!     Close
      close(22)
      
      deallocate(aux) 

      if (IDISPLAY.eq.1) then
         print*,' '
         print*,' ==================================================='
         print*,'         Gmesh data was succesfully read            '
         print*,' ==================================================='
         print*,' '
      endif
                   
!*********************************************************************!
!                                                                     !
!                Making the all the components of the file            !
!                                                                     !
!*********************************************************************!

!      ________________________________________________________
!     |                                                        |
!     |                         Allocate                       |
!     |________________________________________________________|

      allocate(c1(TotalE),c2(TotalE),c3(TotalE))
      allocate(BottomH(TotalV))
      allocate(tbe(TotalE),tbv(TotalV))
      allocate(vbdy1(TotalV),vbdy2(TotalV),vbdy3(TotalV))
      allocate(Esample(Nesample),Vsample(Nvsample))

!      ________________________________________________________
!     |                                                        |
!     |           Numbering of cell center neighbors           |
!     |________________________________________________________|

      do i=1,totalE
         c1(i) = 0
         c2(i) = 0
         c3(i) = 0
!        -----------------------------------------
!        Edge 1
         vertex1 =  v1(i)
         vertex2 =  v2(i)
         do nc=1,totalE
            if (nc.ne.i) then
               if (v1(nc).eq.vertex1) then
                  if ((v2(nc).eq.vertex2).or.(v3(nc).eq.vertex2)) c1(i)=nc
               elseif (v2(nc).eq.vertex1) then
                  if ((v3(nc).eq.vertex2).or.(v1(nc).eq.vertex2)) c1(i)=nc
               elseif (v3(nc).eq.vertex1) then
                  if ((v1(nc).eq.vertex2).or.(v2(nc).eq.vertex2)) c1(i)=nc
               endif
            endif
         enddo
!        -----------------------------------------
!        Edge 2
         vertex1 =  v2(i)
         vertex2 =  v3(i)
         do nc=1,totalE
            if (nc.ne.i) then
               if (v1(nc).eq.vertex1) then
                  if ((v2(nc).eq.vertex2).or.(v3(nc).eq.vertex2)) c2(i)=nc
               elseif (v2(nc).eq.vertex1) then
                  if ((v3(nc).eq.vertex2).or.(v1(nc).eq.vertex2)) c2(i)=nc
               elseif (v3(nc).eq.vertex1) then
                  if ((v1(nc).eq.vertex2).or.(v2(nc).eq.vertex2)) c2(i)=nc
               endif
            endif
         enddo
!        -----------------------------------------
!        Edge 3
         vertex1 =  v3(i)
         vertex2 =  v1(i)
         do nc=1,totalE
            if ((nc.ne.i)) then
               if (v1(nc).eq.vertex1) then
                  if ((v2(nc).eq.vertex2).or.(v3(nc).eq.vertex2)) c3(i)=nc
               elseif (v2(nc).eq.vertex1) then
                  if ((v3(nc).eq.vertex2).or.(v1(nc).eq.vertex2)) c3(i)=nc
               elseif (v3(nc).eq.vertex1) then
                  if ((v1(nc).eq.vertex2).or.(v2(nc).eq.vertex2)) c3(i)=nc
               endif
            endif
         enddo
       enddo

!      ________________________________________________________
!     |                                                        |
!     |                      Bottom levels                     |
!     |________________________________________________________|

      do nv=1,TotalV
         BottomH(nv) = 1.0d0
      enddo

!      ________________________________________________________
!     |                                                        |
!     |                  Cell-centers (xc,yc)                  |
!     |________________________________________________________|

      do i=1,TotalE
	     jv1 = v1(i)
	     jv2 = v2(i)
	     jv3 = v3(i)              
	     xxc(i)=(xxv(jv1)+xxv(jv2)+xxv(jv3))/3.0d0
	     yyc(i)=(yyv(jv1)+yyv(jv2)+yyv(jv3))/3.0d0
       enddo
       
!      ________________________________________________________
!     |========================================================|
!     |             Tag of boundary element (automatic)         |
!     |________________________________________________________|

!     --------------------------------------
!     NBE general wall
      do i=1,totalE
         tbe(i) = 0
         if ((c1(i).eq.0).or.(c2(i).eq.0).or.(c3(i).eq.0)) then
            tbe(i) = 1
         endif
       enddo
!     --------------------------------------
!     NBEV Vertex tags according to NBE
      do i=1,totalE
         if (tbe(i).eq.1) then
            jv1 = v1(i)
            jv2 = v2(i)
            jv3 = v3(i)        
            if (c1(i).eq.0) then
               tag1(jv1) = 1
               tag1(jv2) = 1            
            endif
            if (c2(i).eq.0) then
               tag1(jv2) = 1
               tag1(jv3) = 1            
            endif
            if (c3(i).eq.0) then
               tag1(jv3) = 1
               tag1(jv1) = 1
            endif
         endif
      enddo

!      ________________________________________________________
!     |========================================================|
!     |              Number of boundary vertices               |
!     |________________________________________________________|


!     --------------------------------------
      Nvwallsbdy = 0
      Nvdischbdy = 0
      Nvwaterbdy = 0
      do nv=1,TotalV
         if (tag1(nv).eq.1) then
            Nvwallsbdy = Nvwallsbdy +1
            vbdy1(Nvwallsbdy) = nv
         elseif (tag1(nv).eq.2) then
            Nvdischbdy = Nvdischbdy + 1
            vbdy2(Nvdischbdy) = nv 
         elseif (tag1(nv).eq.3) then
            Nvwaterbdy = Nvwaterbdy + 1
            vbdy3(Nvwaterbdy) = nv
         endif
      enddo             

!      ________________________________________________________
!     |                                                        |
!     |                       Sampling                         |
!     |________________________________________________________|

!     ---------------------------------
!     Sampling
      Nesample = 2
      Nvsample = 2
!     ---------------------------------
!     Element
      Esample(1) = floor(TotalE/2.0d0) 
      Esample(2) = floor(TotalE/4.0d0)
!     ---------------------------------
!     Vertex
      Vsample(1) = floor(TotalV/2.0d0) 
      Vsample(2) = floor(TotalV/4.0d0)


!*********************************************************************!
!                                                                     !
!                            Write file                               !
!                          -  data.txt                                !
!                                                                     !
!*********************************************************************!

10    format(50a)
11    format(3i8)
12    format(2f15.5)
13    format(10f8.3)
14    format(20i7)
15    format(i8)
!      ________________________________________________________
!     |                                                        |
!     |                    Open saving file                    |
!     |________________________________________________________|

      irec=600
      open(irec,file='data.txt')
!      __________________________________
!     |                                  |
!     |  NUMBER OF CELL-CENTER & VERTEX  |
!     |__________________________________| 

      write(irec,10)'-------- NUMBER OF VERTEX AND CELL-CENTER POINTS --------'
      write(irec,15) TotalV
      write(irec,15) TotalE
!      __________________________________
!     |                                  |
!     |    NUMBERING OF CELL VERTICES    |
!     |__________________________________| 

      write(irec,10)'-------- NUMBERING OF CELL VERTICES --------'
      do nc=1,TotalE
         write(irec,11) v1(nc),v2(nc),v3(nc)
      enddo

!      __________________________________
!     |                                  |
!     |   COORDINATES OF CELL VERTICES   |
!     |__________________________________| 

      write(irec,10)'-------- COORDINATES OF CELL VERTICES --------'
      do nv=1,TotalV
         write(irec,12) xxv(nv),yyv(nv)
      enddo

!      __________________________________
!     |                                  |
!     |     NUMBERING OF CELL CENTERS    |
!     |__________________________________| 

      write(irec,10)'-------- NUMBERING OF CELL CENTERS --------'
      do nc=1,TotalE
         write(irec,11) c1(nc),c2(nc),c3(nc)
      enddo

!      __________________________________
!     |                                  |
!     |           BOTTOM LEVELS          |
!     |__________________________________| 

      write(irec,10)'-------- BOTTOM LEVELS --------'
      write(irec,13) BottomH(1:TotalV)

!      __________________________________
!     |                                  |
!     |      TYPE OF BOUNDARY CELLS      |
!     |__________________________________| 

      write(irec,10)'-------- TYPE OF BOUNDARY CELLS --------'
      write(irec,14) tbe(1:TotalE)
      
!      __________________________________
!     |                                  |
!     |   NUMBER OF WALL BOUNDARY VERT   |
!     |__________________________________|

      write(irec,10)'-------- NUMBER OF WALL BOUNDARY VERTICES --------'
      write(irec,15) Nvwallsbdy
      write(irec,14) vbdy1(1:Nvwallsbdy)

!      __________________________________
!     |                                  |
!     |NUMBER OF DISCHARGE BOUNDARY VERT |
!     |__________________________________|

      write(irec,10)'-------- NUMBER OF DISCHARGE BOUNDARY VERTICES --------'
      write(irec,15) Nvdischbdy
      write(irec,14) vbdy2(1:Nvdischbdy)

!      __________________________________
!     |                                  |
!     |   NUMBER OF WATER BOUNDARY VERT  |
!     |__________________________________|

      write(irec,10)'-------- NUMBER OF WATER BOUNDARY VERTICES --------'
      write(irec,15) Nvwaterbdy
      write(irec,14) vbdy3(1:Nvwaterbdy)

!      __________________________________
!     |                                  |
!     |     NUMBER OF SAMPLING VERT      |
!     |__________________________________|

      write(irec,10)'-------- NUMBER OF SAMPLING VERTICES --------'      
      write(irec,15) Nvsample
      write(irec,14) Esample(1:Nvsample)

!      ________________________________________________________
!     |                                                        |
!     |                   Closing saving file                  |
!     |________________________________________________________|

      close(irec)

!*********************************************************************!
!                                                                     !
!                Write the Pseudo-Grid to divide the domain           !
!                         -  data.graph                               !
!                         -  data.coords                              !
!                                                                     !
!*********************************************************************!


!      ________________________________________________________
!     |                                                        |
!     |                 Write Chaco data files                 |
!     |________________________________________________________|

21    format(2i8)
22    format(2f15.5)
23    format(3f15.5)
24    format(3i8)


!*********************************************************************!
!                                                                     !
!                           Finalization                              !
!                                                                     !
!*********************************************************************!

!      ________________________________________________________
!     |                                                        |
!     |                   Display information                  |
!     |________________________________________________________|

      write(*,*) ' '
      write(*,'(t8,60a)')'---------------------------------------------'
      write(*,'(t8,60a)')' Generation of the data from BlueKenue mesh  '
      write(*,'(t8,60a)')'---------------------------------------------'
      write(*,'(t8,a15,i8)')'    Vertices = ',TotalV
      write(*,'(t8,a15,i8)')'    Elements = ',TotalE
      write(*,'(t8,60a)')'---------------------------------------------'
      write(*,*) ' '
      write(*,'(t8,60a)')'  saved:  nsmp3D/input/data.txt              '
      write(*,'(t8,60a)')'  saved:  nsmp3D/Chaco-2.2/exec/data.graph   '
      write(*,'(t8,60a)')'  saved:  nsmp3D/Chaco-2.2/exec/data.coords  '
      write(*,*) ' '
      write(*,'(t8,60a)')'---------------------------------------------'
      write(*,*) ' '

!      ________________________________________________________
!     |                                                        |
!     |                       Deallocate                       |
!     |________________________________________________________|

      deallocate(xxv,yyv,           &
                 xxc,yyc,           &
                 v1,v2,v3,          &
                 tag1)

      deallocate(c1,c2,c3,          &
                 BottomH,           &
                 tbe,tbv,           &
                 vbdy1,vbdy2,vbdy3, &
                 Esample,VSample)

!     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     ifdef KeyDbg
        write(*,'(t8,60a)') '----> End   subroutine: MeshBlueKenue'
#     endif
!     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      RETURN
      END

!wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww!
!---------------------------------------------------------------------!
!                     END OF MESHGENERATOR BlueKenue                  !
!                              Jun 2013                               !
!---------------------------------------------------------------------!
!wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww!

